/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.asmduan1;

import com.QLKhachSan.dao.QLDatPhong;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author AD
 */
public class frm_form extends javax.swing.JFrame {
    private Timer timer;

    /**
     * Creates new form frm_form
     */
    public frm_form() {
        initComponents();
        startClock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Phòng = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_DongHo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_DatPhong = new javax.swing.JButton();
        btn_KhachHang = new javax.swing.JButton();
        btn_KetThuc = new javax.swing.JButton();
        btn_DangXuat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        aa = new javax.swing.JMenu();
        mnui_DangXuat = new javax.swing.JMenuItem();
        mnui_Thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnui_QLPhong = new javax.swing.JMenuItem();
        qldatphong = new javax.swing.JMenuItem();
        QLKhachHang = new javax.swing.JMenuItem();
        QLThanhToan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcesanh/BackGroundKhachSan.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );

        btn_Phòng.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Phòng.setText("PHÒNG");
        btn_Phòng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhòngActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N

        lbl_DongHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_DongHo.setText("00:00");
        lbl_DongHo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_DongHoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5-stars (1).png"))); // NOI18N

        btn_DatPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DatPhong.setText("ĐẶT PHÒNG");
        btn_DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhongActionPerformed(evt);
            }
        });

        btn_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_KhachHang.setText("KHÁCH HÀNG");
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });

        btn_KetThuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_KetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        btn_KetThuc.setText("KẾT THÚC");
        btn_KetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KetThucActionPerformed(evt);
            }
        });

        btn_DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btn_DangXuat.setText("ĐĂNG XUẤT");
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });

        aa.setText("Hệ thống");

        mnui_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        mnui_DangXuat.setText("Đăng xuất");
        mnui_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnui_DangXuatActionPerformed(evt);
            }
        });
        aa.add(mnui_DangXuat);

        mnui_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        mnui_Thoat.setText("Kết thức");
        mnui_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnui_ThoatActionPerformed(evt);
            }
        });
        aa.add(mnui_Thoat);

        jMenuBar1.add(aa);

        jMenu2.setText("Quản lý");

        mnui_QLPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
        mnui_QLPhong.setText("Quản lý phòng ");
        mnui_QLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnui_QLPhongActionPerformed(evt);
            }
        });
        jMenu2.add(mnui_QLPhong);

        qldatphong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Calendar.png"))); // NOI18N
        qldatphong.setText("Quản lý đặt phòng");
        qldatphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qldatphongActionPerformed(evt);
            }
        });
        jMenu2.add(qldatphong);

        QLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users.png"))); // NOI18N
        QLKhachHang.setText("Quản lý khách hàng");
        QLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLKhachHangActionPerformed(evt);
            }
        });
        jMenu2.add(QLKhachHang);

        QLThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        QLThanhToan.setText("Quản lý thanh toán");
        jMenu2.add(QLThanhToan);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Liên hệ");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_DongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(150, 150, 150)
                                .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Phòng, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_KetThuc)
                                .addGap(18, 18, 18)
                                .addComponent(btn_DangXuat)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Phòng, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_KetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_DongHo))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnui_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnui_ThoatActionPerformed
        hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_mnui_ThoatActionPerformed

    private void qldatphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qldatphongActionPerformed
    QuanLyDatPhong dp = new QuanLyDatPhong();
    dp.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_qldatphongActionPerformed

    private void mnui_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnui_DangXuatActionPerformed
        frmDangNhapND nv = new frmDangNhapND();
        nv.show();
        hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_mnui_DangXuatActionPerformed

    private void mnui_QLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnui_QLPhongActionPerformed
        QuanLiPhong qlp = new QuanLiPhong();
        qlp.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_mnui_QLPhongActionPerformed

    private void btn_PhòngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhòngActionPerformed
        QuanLiPhong qlp = new QuanLiPhong();
        qlp.show();
        hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PhòngActionPerformed

    private void QLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLKhachHangActionPerformed
        frm_QLKH qlkh = new frm_QLKH();
        qlkh.show();
    }//GEN-LAST:event_QLKhachHangActionPerformed

    private void btn_DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhongActionPerformed
        QuanLyDatPhong qldp = new QuanLyDatPhong();
        qldp.show();
    }//GEN-LAST:event_btn_DatPhongActionPerformed

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        frm_QLKH qlkh = new frm_QLKH();
    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_KetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KetThucActionPerformed
        hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_KetThucActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        frm_DangNhap ql = new frm_DangNhap();
        ql.show();
        hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void lbl_DongHoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_DongHoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_DongHoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem QLKhachHang;
    private javax.swing.JMenuItem QLThanhToan;
    private javax.swing.JMenu aa;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_DatPhong;
    private javax.swing.JButton btn_KetThuc;
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_Phòng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_DongHo;
    private javax.swing.JMenuItem mnui_DangXuat;
    private javax.swing.JMenuItem mnui_QLPhong;
    private javax.swing.JMenuItem mnui_Thoat;
    private javax.swing.JMenuItem qldatphong;
    // End of variables declaration//GEN-END:variables
    private void startClock() {
        // Create a timer that fires every second
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateClock();
            }
        });
        // Start the timer
        timer.start();
    }
    private void updateClock() {
        // Get the current time and format it
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String time = sdf.format(new Date());
        // Set the formatted time to lbl_DongHo
        lbl_DongHo.setText(time);
    }
}
